### ISSUE TITLE
Add option to save jars to project folder

### ISSUE THREAD

**Issue by codeanticode** [nekocode/Gradle-Import-Aar#3]
@nekocode I see you made this as a gradle plugin, awesome!

I would use it in [Processing for Android](https://github.com/processing/processing-android) (currently just using the transform code manually in the gradle build files), except that in [one situation](https://github.com/processing/processing-android/blob/master/mode/libraries/vr/build.gradle#L79) I need to save the exploded jars to a location inside my project. Would be nice to have this as a feature of the plugin somehow. 

Thanks for this very useful work!

**Comment by nekocode** [comment]
Sorry for my late reply.

You can use below code to copy the resolved dependency files (jars in aars) to your target directory:

```
project.afterEvaluate {
    it.configurations.getByName("aarCompileOnly").forEach { jarFile ->
        // copy to somewhere
    }
}
```

**Comment by codeanticode** [comment]
Very cool, thank you!
